### PR TITLE
Do not fail on unknown algorithms (fix #66)

### LINKED ISSUE #66: Ignore unknown CTAP response fields
New versions of the specifications frequently add new fields. Ignoring new fields allow previous versions of the library not to fail when used with newer devices. See #65.

We may need to fork serde_indexed to add this functionality.

### PR DESCRIPTION
**Pull request by AlfioEmanueleFresta**
Allows parsing unknown algorithm types without failing.

Only ES256 is every used for requests, and it's guaranteed to be supported by the spec, so checking the value is not necessary for now.

### CODE REVIEW

File: libwebauthn/src/proto/ctap1/model.rs [hunk 1]
```diff
@@ -12,20 +12,21 @@ use crate::webauthn::CtapError;
 
 #[derive(Debug, Clone, Copy)]
 pub enum Ctap1Transport {
-    BT,
-    BLE,
-    NFC,
-    USB,
+    Bt,
```
Comment (msirringhaus) [inline libwebauthn/src/proto/ctap1/model.rs]: Probably needs rebasing on HEAD?

File: libwebauthn/src/proto/ctap2/model/credential_protection.rs [hunk 2]
```diff
@@ -0,0 +1,22 @@
+use minicbor::{Decode, Encode};
```
Comment (msirringhaus) [inline libwebauthn/src/proto/ctap2/model/credential_protection.rs]: This file is here again :D

File: libwebauthn/src/proto/ctap2/model.rs [hunk 3]
```diff
@@ -242,4 +253,44 @@ mod tests {
...
+            Ctap2CredentialType {
+                algorithm: Ctap2COSEAlgorithmIdentifier::Unknown,
+                public_key_type: Ctap2PublicKeyCredentialType::PublicKey,
+            }
+        );
+        assert!(!credential_type.is_known());
+    }
+
+    #[test]
+    pub fn deerialize_unknown_credential_type() {
```
Comment (msirringhaus) [inline libwebauthn/src/proto/ctap2/model.rs]: typo. `deerialize`

**Review by msirringhaus — CHANGES_REQUESTED** [review]

File: libwebauthn/src/proto/ctap2/model/credential_protection.rs (hunk 2 above)
Comment (AlfioEmanueleFresta) [reply libwebauthn/src/proto/ctap2/model/credential_protection.rs]: Sorry!
